### ISSUE TITLE
ImportError: cannot import name MongoEngineModelSerializer

### ISSUE THREAD

**Issue by jonasli** [umutbozkurt/django-rest-framework-mongoengine#205]
I had installed the DRF-mongoengine

Successfully installed django-rest-framework-mongoengine-3.3.1

and add it to the settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
    'rest_framework',
    'rest_framework_mongoengine',
]

and in my serializers.py file , import the serializer 

from rest_framework_mongoengine.serializers import MongoEngineModelSerializer

class UserSerializer(MongoEngineModelSerializer):
    class Meta:
        model = user

but I still got the error  

  File "/home/jonas/django/mysite/blog/serializers.py", line 1, in <module>
    from rest_framework_mongoengine.serializers import MongoEngineModelSerializer
ImportError: cannot import name MongoEngineModelSerializer

can you please help me on this ?

thanks very much,
J

**Comment by BurkovBA** [comment]
@jonasli 

Hi! You  should just `import DocumentSerializer`. :)

**Comment by jonasli** [comment]
thank you @BurkovBA  .

but it doesn't work :(
File "/home/jonas/django/mysite/blog/serializers.py", line 1, in <module>
    from rest_framework_mongoengine import DocumentSerializer
ImportError: cannot import name DocumentSerializer


and I'm following the guide 

https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/drf_2_support/README.md

what is wrong here ?

**Comment by BurkovBA** [comment]
Oh, I'm very sorry `from rest_framework_mongoengine.serializers import DocumentSerializer`.

 The README, you're following is very outdated.

Try [this example](https://github.com/BurkovBA/django-rest-framework-mongoengine-example) and [this article](https://medium.com/@vasjaforutube/django-mongodb-django-rest-framework-mongoengine-ee4eb5857b9a#.1zpkbvpc6). :)

**Comment by jonasli** [comment]
@BurkovBA  thank you for reply.

I tried to use the routers.py in your example, just copy and paste your code, but I got the error below, do you happen to know the cause ? I appreciate . 

 Performing system checks...

Unhandled exception in thread started by <function wrapper at 0xb61ebaac>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jonas/django/mysite/mysite/urls.py", line 22, in <module>
    url(r'^blog/', include('blog.urls',namespace="blog")),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jonas/django/mysite/blog/urls.py", line 19, in <module>
    url(r'^api/',include(router.urls,namespace='api')),
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/routers.py", line 83, in urls
    self._urls = self.get_urls()
  File "/home/jonas/django/mysite/blog/routers.py", line 30, in get_urls
    urls = super(HybridRouter, self).get_urls()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/routers.py", line 379, in get_urls
    view = self.get_api_root_view(api_urls=urls)
**TypeError: get_api_root_view() got an unexpected keyword argument 'api_urls'**

**Comment by BurkovBA** [comment]
@jonasli 
Sorry about that - this code was written for DRF 3.3.3 and they changed the router in DRF 3.4+, so now it breaks. For now just use the standard `DefaultRouter` from  DRF-Mongoengine instead: `from rest_framework_mongoengine import DefaultRouter`.

**Comment by jonasli** [comment]
@BurkovBA thank you , I can make it run at least now. :)

**Comment by G-linch** [comment]
@jonasli  i got the same  typeerror.

but i also can not fix it.
i dont konw how to change the code  .


For now just use the standard DefaultRouter from DRF-Mongoengine instead: from rest_framework_mongoengine import DefaultRouter.

which py file?

**Comment by BurkovBA** [comment]
@G-linch 

Thanks for reporting this. Most probably, those are issues with changes to router in DRF 3.5. I'll have to take a closer look. In your `routers.py` replace 

`from rest_framework.routers import DefaultRouter`

with

`from rest_framework_mongoengine import DefaultRouter`

if that still doesn't work, please, let me know. :)

**Comment by G-linch** [comment]
I use pycharm.When I import DefaultRouter from rest_framework_mongoengine,ide canot find  DefaultRouter,i search the  rest_framework_mongoengine,find  the  DefaultRouter in routers.py,so i add the routers like this :from rest_framework_mongoengine.routers import DefaultRouter,but it still doesn't work.check the DefaultRouter from  rest_framework_mongoengine.routers which show pass under the class DefaultRouter,i would follow the requirements.txt and have a try.

**Comment by BurkovBA** [comment]
Oh, sorry, `from rest_framework_mongoengine.routers` indeed. You might also need to replace `def get_qeryset(self)` in your viewsets with just an attribute queryset, e.g. `queryset = Tool.objects.all()`: https://github.com/BurkovBA/django-rest-framework-mongoengine-example/blob/master/project/app/views.py.

**Comment by G-linch** [comment]
You mean this?  in views.py under class
def get_queryset(self):
        return Tool.objects.all()

how can i rewrite it?

**Comment by G-linch** [comment]
finally i fixed it.   i pip install -r requirements.txt,and it run.it mostly the versions difference.thanks.

**Comment by BurkovBA** [comment]
@G-linch Great!

For newer versions of DRF, use the solution in my previous message.
