### ISSUE TITLE
AttributeError: 'User' object has no attribute '_dynamic'

### ISSUE THREAD

**Issue by Axik** [umutbozkurt/django-rest-framework-mongoengine#52]
##views.py

```python
from rest_framework import generics

from .models import User
from .serializers import UserListSerializer

class UserList(generics.ListCreateAPIView):
    queryset = User.objects.all()
    paginate_by = 100
    serializer_class = UserListSerializer


user_list = UserList.as_view()
```

##models.py

```python
import binascii
import os

from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):

    token = models.CharField(name='Token', blank=True, max_length=50)

    def __unicode__(self):
        return self.username

    class Meta:
        db_table = 'users'

    @staticmethod
    def generate_token():
        return binascii.hexlify(os.urandom(20)).decode()

    def make_new_token(self):
        self.token = self.generate_token()
        return self.save()
```

##serializers.py
```python
from rest_framework_mongoengine.serializers import MongoEngineModelSerializer
from .models import User

class UserListSerializer(MongoEngineModelSerializer):
    class Meta:
        model = User
        depth = 2
        exclude = ('password',)
```

Full traceback:
```shell
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/nonrel/src/django/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/nonrel/src/django/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/nonrel/src/django/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework/views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework/generics.py", line 493, in get
    return self.list(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 98, in list
    return Response(serializer.data)
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 576, in data
    self._data = self.to_native(obj)
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 355, in to_native
    value = field.field_to_native(obj, field_name)
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 414, in field_to_native
    return [self.to_native(item) for item in value.all()]
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework_mongoengine/serializers.py", line 203, in to_native
    dynamic_fields = self.get_dynamic_fields(obj)
  File "/home/vagrant/.virtualenvs/nonrel/local/lib/python2.7/site-packages/rest_framework_mongoengine/serializers.py", line 131, in get_dynamic_fields
    if obj is not None and obj._dynamic:
AttributeError: 'User' object has no attribute '_dynamic'
```

**Comment by umutbozkurt** [comment]
Your `User` model is not a mongodb document. If you want to use auth user model, you should
use mongoengine's user model(django user model replicated for mongodb)
`from mongoengine.django.auth import User`
